"""убрал поля head_id deputy_id

Revision ID: 6b8edc74fd77
Revises: e1714542eef2
Create Date: 2026-08-21 11:31:57.628907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8edc74fd77'
down_revision: Union[str, Sequence[str], None] = 'e1714542eef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('departments_deputy_head_id_key'), 'departments', type_='unique')
    op.drop_constraint(op.f('departments_head_id_key'), 'departments', type_='unique')
    op.drop_constraint(op.f('departments_head_id_fkey'), 'departments', type_='foreignkey')
    op.drop_constraint(op.f('departments_deputy_head_id_fkey'), 'departments', type_='foreignkey')
    op.drop_column('departments', 'head_id')
    op.drop_column('departments', 'deputy_head_id')
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True, comment='Отдел'))
    op.drop_constraint(op.f('users_department_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.INTEGER(), autoincrement=False, nullable=True, comment='Отдел'))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_department_fkey'), 'users', 'departments', ['department'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'department_id')
    op.add_column('departments', sa.Column('deputy_head_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Заместитель начальника отдела'))
    op.add_column('departments', sa.Column('head_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Начальник отдела'))
    op.create_foreign_key(op.f('departments_deputy_head_id_fkey'), 'departments', 'users', ['deputy_head_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('departments_head_id_fkey'), 'departments', 'users', ['head_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('departments_head_id_key'), 'departments', ['head_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('departments_deputy_head_id_key'), 'departments', ['deputy_head_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
