"""изменил связь отдела с начем на один к одному

Revision ID: 850694e4bf77
Revises: 88dc43fdb671
Create Date: 2026-08-19 11:30:04.579668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850694e4bf77'
down_revision: Union[str, Sequence[str], None] = '88dc43fdb671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'departments', ['deputy_head_id'])
    op.create_unique_constraint(None, 'departments', ['head_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='unique')
    op.drop_constraint(None, 'departments', type_='unique')
    # ### end Alembic commands ###
