"""добавил сроки deadlines

Revision ID: 24683ed9f658
Revises: 5eef04410444
Create Date: 2026-09-04 09:04:19.541558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24683ed9f658'
down_revision: Union[str, Sequence[str], None] = '5eef04410444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deadlines', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deadlines')
    # ### end Alembic commands ###
