"""добавил m2m dep_tasks

Revision ID: e1714542eef2
Revises: d4cd49a3555a
Create Date: 2026-08-20 18:16:52.593151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1714542eef2'
down_revision: Union[str, Sequence[str], None] = 'd4cd49a3555a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Bishkek', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('Asia/Bishkek', now())"), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'task_id', name='uq_departments_tasks_department_id_task_id')
    )
    op.drop_constraint(op.f('tasks_department_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tasks_department_id_fkey'), 'tasks', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_table('departments_tasks')
    # ### end Alembic commands ###
