"""привязал исполнителя к ответу

Revision ID: 9643a99756f5
Revises: 1a8efc60eabc
Create Date: 2026-09-01 16:15:39.878946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9643a99756f5'
down_revision: Union[str, Sequence[str], None] = '1a8efc60eabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_replies', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_replies', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_replies', type_='foreignkey')
    op.drop_column('task_replies', 'author_id')
    # ### end Alembic commands ###
