"""add status for task

Revision ID: 5eef04410444
Revises: 9643a99756f5
Create Date: 2026-09-03 14:55:55.135395

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eef04410444'
down_revision: Union[str, Sequence[str], None] = '9643a99756f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

task_status_enum = postgresql.ENUM("NEW", "PROGRESS", "DONE", name="tasksstatus")

def upgrade() -> None:
    """Upgrade schema."""
    task_status_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.Enum('NEW', 'PROGRESS', 'DONE', name='tasksstatus'), server_default='NEW', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
