"""Добавил начальников и замов к отделам

Revision ID: 88dc43fdb671
Revises: b6e1295c511c
Create Date: 2026-08-18 16:38:18.867495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88dc43fdb671'
down_revision: Union[str, Sequence[str], None] = 'b6e1295c511c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('head_id', sa.Integer(), nullable=True, comment='Начальник отдела'))
    op.add_column('departments', sa.Column('deputy_head_id', sa.Integer(), nullable=True, comment='Заместитель начальника отдела'))
    op.create_foreign_key(None, 'departments', 'users', ['head_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'departments', 'users', ['deputy_head_id'], ['id'], ondelete='SET NULL')
    op.create_check_constraint('check_head_and_deputy_different', 'departments', 'head_id IS NULL OR deputy_head_id IS NULL OR head_id <> deputy_head_id')
    op.create_unique_constraint('uq_users_tasks_user_id_task_id', 'users_tasks', ['user_id', 'task_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_tasks_user_id_task_id', 'users_tasks', type_='unique')
    op.drop_constraint('check_head_and_deputy_different', 'departments', type_='check')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'deputy_head_id')
    op.drop_column('departments', 'head_id')
    # ### end Alembic commands ###
